name: notifier
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  shared_preferences:
  hive: ^1.4.1+1
  hive_flutter: 
  flutter_spinkit: "^4.1.2"
  intl:
  google_maps_flutter: ^0.5.27+1
  google_fonts: ^1.0.0
  # simple_animations: ^1.3.12
  flutter_calendar_carousel: ^1.5.1
  googleapis_auth: ^0.2.12
  googleapis: ^0.56.1
  syncfusion_flutter_calendar: ^18.3.42
  table_calendar: ^2.3.0
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_datetime_picker: ^1.4.0
  flutter_icons: ^1.1.0
  async: ^2.4.0
  # firebase_database: ^3.0.7
  cloud_firestore:
  path_provider:
  image_picker:
  geolocator:
  # mongo_dart:
  #   git:
  #       url: "https://github.com/tgercek/mongo_dart.git"
  connectivity: ^0.4.8
  # frideos: ^1.0.0+1
  # scoped_model: ^1.0.1
  sqflite: ^1.3.0
  # network_to_file_image: ^2.3.0
  # image_gallery_saver: ^1.2.2
  # image: ^2.1.12
  # image_downloader: ^0.19.2
  # flutter_full_pdf_viewer: ^1.0.6
  # flutter_image: ^3.0.0
  # dio: ^3.0.9
  firebase_storage:
  cached_network_image: ^2.0.0-rc
  liquid_pull_to_refresh: ^1.1.2
  # bot_toast: ^2.4.0
  flutter_styled_toast: ^1.2.1
  auto_size_text: ^2.1.0
  flutter_local_notifications:
  url_launcher:
  # flutter_linkify:
    #  notification_reactor: ^0.0.3+1
  # sliding_up_panel:
  # firebase_core:
  firebase_messaging:
  keyboard_visibility: ^0.5.6
  # flutter_email_sender: ^3.0.1
  # recase: ^2.0.1
  # fluttertoast:
  http:
  dynamic_theme:
  qr_flutter: ^3.1.0
  # webview_flutter:
  # app_review: ^1.1.0+1
  rate_my_app:
  feature_discovery: ^0.8.0
  # get_it: ^1.0.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  # hive_generator: ^0.7.0+2
  # build_runner: ^1.9.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/data.json
    - assets/launch.png
    - assets/Aditya.png
    - assets/Utkarsh1.jpg
    - assets/wdLogo.png
    - assets/
    - assets/map-styles/
    - lib/screens/maps/assets/
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa/static/Comfortaa-Regular.ttf
            # - asset: assets/static/Nunito-LightItalic.ttf
            #   style: italic
    - family: Raleway
      fonts:
        - asset: assets/Raleway/Raleway-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/Nunito/Nunito-Regular.ttf
      #       - asset: fonts/TrajanPro_Bold.ttf
      #         weight: 700
      #
      # For details regarding fonts from package dependencies,
      # see https://flutter.dev/custom-fonts/#from-packages
